// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/DeadlyParkour777/pr-service/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// PullRequestRepository is an autogenerated mock type for the PullRequestRepository type
type PullRequestRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, pr
func (_m *PullRequestRepository) Create(ctx context.Context, pr model.PullRequest) error {
	ret := _m.Called(ctx, pr)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.PullRequest) error); ok {
		r0 = rf(ctx, pr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *PullRequestRepository) GetByID(ctx context.Context, id string) (*model.PullRequest, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.PullRequest, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.PullRequest); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByReviewerID provides a mock function with given fields: ctx, reviewerID
func (_m *PullRequestRepository) GetByReviewerID(ctx context.Context, reviewerID string) ([]model.PullRequest, error) {
	ret := _m.Called(ctx, reviewerID)

	if len(ret) == 0 {
		panic("no return value specified for GetByReviewerID")
	}

	var r0 []model.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.PullRequest, error)); ok {
		return rf(ctx, reviewerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.PullRequest); ok {
		r0 = rf(ctx, reviewerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, reviewerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Merge provides a mock function with given fields: ctx, id
func (_m *PullRequestRepository) Merge(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Merge")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReassignReviewer provides a mock function with given fields: ctx, prID, oldReviewerID, newReviewerID
func (_m *PullRequestRepository) ReassignReviewer(ctx context.Context, prID string, oldReviewerID string, newReviewerID string) error {
	ret := _m.Called(ctx, prID, oldReviewerID, newReviewerID)

	if len(ret) == 0 {
		panic("no return value specified for ReassignReviewer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, prID, oldReviewerID, newReviewerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPullRequestRepository creates a new instance of PullRequestRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPullRequestRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PullRequestRepository {
	mock := &PullRequestRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
