// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/DeadlyParkour777/pr-service/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// TeamRepository is an autogenerated mock type for the TeamRepository type
type TeamRepository struct {
	mock.Mock
}

// AddTeamWithMembers provides a mock function with given fields: ctx, team, members
func (_m *TeamRepository) AddTeamWithMembers(ctx context.Context, team model.Team, members []model.User) (*model.Team, error) {
	ret := _m.Called(ctx, team, members)

	if len(ret) == 0 {
		panic("no return value specified for AddTeamWithMembers")
	}

	var r0 *model.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Team, []model.User) (*model.Team, error)); ok {
		return rf(ctx, team, members)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Team, []model.User) *model.Team); ok {
		r0 = rf(ctx, team, members)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Team, []model.User) error); ok {
		r1 = rf(ctx, team, members)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByName provides a mock function with given fields: ctx, name
func (_m *TeamRepository) GetByName(ctx context.Context, name string) (*model.Team, []model.User, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 *model.Team
	var r1 []model.User
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Team, []model.User, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Team); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) []model.User); ok {
		r1 = rf(ctx, name)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]model.User)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, name)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewTeamRepository creates a new instance of TeamRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTeamRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TeamRepository {
	mock := &TeamRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
