// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/DeadlyParkour777/pr-service/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

// GetActiveTeamMembers provides a mock function with given fields: ctx, teamID, excludeUserID
func (_m *UserRepository) GetActiveTeamMembers(ctx context.Context, teamID int, excludeUserID string) ([]model.User, error) {
	ret := _m.Called(ctx, teamID, excludeUserID)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveTeamMembers")
	}

	var r0 []model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string) ([]model.User, error)); ok {
		return rf(ctx, teamID, excludeUserID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, string) []model.User); ok {
		r0 = rf(ctx, teamID, excludeUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, string) error); ok {
		r1 = rf(ctx, teamID, excludeUserID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *UserRepository) GetByID(ctx context.Context, id string) (*model.FullUserInfo, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.FullUserInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.FullUserInfo, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.FullUserInfo); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.FullUserInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetIsActive provides a mock function with given fields: ctx, id, isActive
func (_m *UserRepository) SetIsActive(ctx context.Context, id string, isActive bool) (*model.FullUserInfo, error) {
	ret := _m.Called(ctx, id, isActive)

	if len(ret) == 0 {
		panic("no return value specified for SetIsActive")
	}

	var r0 *model.FullUserInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) (*model.FullUserInfo, error)); ok {
		return rf(ctx, id, isActive)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) *model.FullUserInfo); ok {
		r0 = rf(ctx, id, isActive)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.FullUserInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, bool) error); ok {
		r1 = rf(ctx, id, isActive)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
